name:    moot
version: "0.0.0"
license: AGPL

default-extensions:
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DeriveDataTypeable
  - DeriveGeneric
  - EmptyDataDecls
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TemplateHaskell
  - TupleSections
  - TypeFamilies
  - TypeOperators
  - ViewPatterns

dependencies:
# Due to a bug in GHC 8.0.1, we block its usage
# See: https://ghc.haskell.org/trac/ghc/ticket/12130
- base >=4.8.2.0 && <4.9 || >=4.9.1.0 && <5

- aeson >=0.6 && <1.3
- array
- base16-bytestring
- bcrypt >= 0.0.8 && < 0.0.12
- blaze-html
- bytestring >=0.9 && <0.11
- case-insensitive
- classy-prelude >=1.4 && <1.5
- classy-prelude-conduit >=1.4 && <1.5
- classy-prelude-yesod >=1.4 && <1.5
- conduit >=1.0 && <2.0
- containers
- cryptohash
- data-default
- directory >=1.1 && <1.4
- email-validate
- errors
- esqueleto >= 2.5 && < 2.7
- fast-logger >=2.2 && <2.5
- file-embed
- foreign-store
- hjsmin >=0.1 && <0.3
- http-client-tls >=0.3 && <0.4
- http-conduit >=2.3 && <2.4
- http-types
- monad-control >=0.3 && <1.1
- monad-logger >=0.3 && <0.4
- persistent >=2.8 && <2.9
- persistent-postgresql >=2.8 && <2.9
- persistent-template >=2.5 && <2.9
- random
- safe
- shakespeare >=2.0 && <2.1
- template-haskell
- text >=0.11 && <2.0
- transformers
- time
- unordered-containers
- vector
- wai
- wai-extra >=3.0 && <3.1
- wai-logger >=2.2 && <2.4
- warp >=3.0 && <3.3
- yaml >=0.8 && <0.9
- yesod >=1.6 && <1.7
- yesod-auth >=1.6 && <1.7
- yesod-core >=1.6 && <1.7
- yesod-form >=1.6 && <1.7
- yesod-persistent
- yesod-static >=1.6 && <1.7

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src
  exposed-modules:
    - Application
    - AppType
    - Foundation
    - Import
    - Model
    - Model.Fixtures
  when:
  - condition: (flag(dev)) || (flag(library-only))
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O2

# Runnable executable for our application
executables:
  moot:
    main: main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - moot
    when:
    - condition: flag(library-only)
      buildable: false
  migration:
    when:
      - condition: flag(library-only)
        buildable: false
    main: Main.hs
    source-dirs:
      - app/migration
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - moot
  fixtures:
    when:
      - condition: flag(library-only)
        buildable: false
    main: Main.hs
    source-dirs:
      - app/fixtures
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - moot
  truncate:
    when:
      - condition: flag(library-only)
        buildable: false
    main: Main.hs
    source-dirs:
      - app/truncate
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - moot

# Test suite
tests:
  moot-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - moot
    - hspec >=2.0.0
    - yesod-test

# Define flags used by "yesod devel" to make compilation faster
flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
